#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Touch.Droid.Resource", IsApplication=true)]

namespace Touch.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int check_me = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int checked_me = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int touch_me = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int coordinatesInfoTextView = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int durationInfoTextView = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int imageView1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int touchImageView = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int touchInfoTextView = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int custom_gesture_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int touch_layout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int gestures = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public const int activity_custom_gesture_recognizer = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int activity_gesture_recognizer = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int activity_touch_sample = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
