#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("com.xamarin.university.mobilenav.android.stack.Resource", IsApplication=true)]

namespace com.xamarin.university.mobilenav.android.stack
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_sessions = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_speakers = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_whats_on = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_launcher = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_tab_my_schedule_selected = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_tab_my_schedule_unselected = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_tab_sessions_selected = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_tab_sessions_unselected = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_tab_speakers_selected = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_tab_speakers_unselected = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_tab_whats_on_selected = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_tab_whats_on_unselected = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int aboutwebview = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int companyNameTextView = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int details = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int headshotImageView = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int locationTextView = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int sessionTitleTextView = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int speakerNameTextView = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int titles_fragment = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int twitterTextView = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int about = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int session_screen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int speaker_row = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int speaker_screen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int speakers_screen = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Plurals
		{
			
			// aapt resource value: 0x7f050000
			public const int speaker_sessions = 2131034112;
			
			static Plurals()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Plurals()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int activity_my_schedule_label = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int activity_sessions_label = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int activity_speakers_label = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int activity_whats_on_label = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int app_name = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
